remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "contrast"

# Site Settings
locale                   : "en-US"
title                    : "evan.network"
title_separator          : "-"
name                     : "Your Name"
description              : "Developer Docs."
url                      : "https://evannetwork.github.io"
repository               : "evannetwork/wiki"
breadcrumbs              : true
breadcrumb_home_label    : "Home"
breadcrumb_separator     : "/"
