remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

# Site Settings
locale                   : "en-US"
title                    : "evan.network"
title_separator          : "-"
name                     : "Your Name"
description              : "An amazing website."
url                      : "https://evannetwork.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "evannetwork/wiki"
