title: evan.network

defaults:
  - scope:
      type: "docs"
    values:
      layout: "default"
  - scope:
      type: "tutorials"
    values:
      layout: "default"
markdown: kramdown
tipue_search:
  include:
    pages: true
  exclude:
    files: []
